// Tests for RecapFormatter — snapshot, parity, determinism, optional field handling

import { describe, expect, it } from 'vitest';
import { formatRecap } from './recap-formatter';
import type { RecapMainTerms } from './recap-formatter';

/** Seed fixture terms — Havila Guardian values used across snapshot tests */
const FULL_TERMS: RecapMainTerms = {
  vessel: 'Havila Guardian',
  vesselType: 'PSV',
  owners: 'Havila Shipping AS',
  charterer: 'Equinor ASA',
  hireRate: '7,500 GBP/day',
  mobilisationFee: '15,000 GBP',
  demobilisationFee: '10,000 GBP',
  deliveryPort: 'Aberdeen',
  redeliveryPort: 'Aberdeen',
  laycanFrom: '2024-06-01',
  laycanTo: '2024-06-07',
  period: '30 days',
  areaOfOperation: 'North Sea',
  workscope: 'Platform Supply',
  governingLaw: 'English Law',
  charterParty: 'SUPPLYTIME 2017',
};

/** Minimal required-only terms (all optional fields null) */
const MINIMAL_TERMS: RecapMainTerms = {
  vessel: 'Sea Explorer',
  vesselType: 'AHTS',
  owners: 'Nordic Offshore Ltd',
  charterer: 'Shell UK',
  hireRate: '12,000 USD/day',
  mobilisationFee: null,
  demobilisationFee: null,
  deliveryPort: null,
  redeliveryPort: null,
  laycanFrom: null,
  laycanTo: null,
  period: '14 days',
  areaOfOperation: 'Norwegian Sea',
  workscope: 'Anchor Handling',
  governingLaw: 'English Law',
  charterParty: 'SUPPLYTIME 2017',
};

describe('RecapFormatter — snapshot tests', () => {
  it('snapshot: full fixture with all fields renders exact Markdown', () => {
    const { markdown } = formatRecap(FULL_TERMS);
    expect(markdown).toBe(
      '# Fixture Recap\n\n' +
      '**Vessel:** Havila Guardian (PSV)\n' +
      '**Owners:** Havila Shipping AS\n' +
      '**Charterer:** Equinor ASA\n' +
      '**Hire Rate:** 7,500 GBP/day\n' +
      '**Mobilisation Fee:** 15,000 GBP\n' +
      '**Demobilisation Fee:** 10,000 GBP\n' +
      '**Delivery:** Aberdeen\n' +
      '**Redelivery:** Aberdeen\n' +
      '**Laycan:** 2024-06-01 to 2024-06-07\n' +
      '**Period:** 30 days\n' +
      '**Area:** North Sea\n' +
      '**Workscope:** Platform Supply\n' +
      '**Charter Party:** SUPPLYTIME 2017\n' +
      '**Governing Law:** English Law\n\n' +
      '---\n' +
      '*Generated by FixtureLog*'
    );
  });

  it('snapshot: full fixture with all fields renders exact plain text', () => {
    const { text } = formatRecap(FULL_TERMS);
    expect(text).toBe(
      'FIXTURE RECAP\n\n' +
      'Vessel: Havila Guardian (PSV)\n' +
      'Owners: Havila Shipping AS\n' +
      'Charterer: Equinor ASA\n' +
      'Hire Rate: 7,500 GBP/day\n' +
      'Mobilisation Fee: 15,000 GBP\n' +
      'Demobilisation Fee: 10,000 GBP\n' +
      'Delivery: Aberdeen\n' +
      'Redelivery: Aberdeen\n' +
      'Laycan: 2024-06-01 to 2024-06-07\n' +
      'Period: 30 days\n' +
      'Area: North Sea\n' +
      'Workscope: Platform Supply\n' +
      'Charter Party: SUPPLYTIME 2017\n' +
      'Governing Law: English Law\n\n' +
      'Generated by FixtureLog'
    );
  });
});

describe('RecapFormatter — optional fields omitted', () => {
  it('omits all optional fields when null — no blank lines in output', () => {
    const { markdown, text } = formatRecap(MINIMAL_TERMS);
    expect(markdown).not.toContain('Mobilisation Fee');
    expect(markdown).not.toContain('Demobilisation Fee');
    expect(markdown).not.toContain('Delivery');
    expect(markdown).not.toContain('Redelivery');
    expect(markdown).not.toContain('Laycan');
    expect(markdown).not.toContain('\n\n\n');
    expect(text).not.toContain('Mobilisation Fee');
    expect(text).not.toContain('\n\n\n');
  });
});

describe('RecapFormatter — Markdown and text parity', () => {
  it('both outputs contain the same field values', () => {
    const { markdown, text } = formatRecap(FULL_TERMS);
    // Required values must appear in both
    for (const value of ['Havila Guardian', '7,500 GBP/day', 'Equinor ASA', 'North Sea']) {
      expect(markdown).toContain(value);
      expect(text).toContain(value);
    }
  });

  it('parity holds for minimal terms — same required fields in both outputs', () => {
    const { markdown, text } = formatRecap(MINIMAL_TERMS);
    for (const value of ['Sea Explorer', '12,000 USD/day', 'Shell UK', 'Norwegian Sea']) {
      expect(markdown).toContain(value);
      expect(text).toContain(value);
    }
  });
});

describe('RecapFormatter — required field completeness', () => {
  it('all 8 required fields present regardless of optional field state', () => {
    const { markdown } = formatRecap(MINIMAL_TERMS);
    expect(markdown).toContain('**Vessel:**');
    expect(markdown).toContain('**Owners:**');
    expect(markdown).toContain('**Charterer:**');
    expect(markdown).toContain('**Hire Rate:**');
    expect(markdown).toContain('**Period:**');
    expect(markdown).toContain('**Area:**');
    expect(markdown).toContain('**Charter Party:**');
    expect(markdown).toContain('**Governing Law:**');
  });
});

describe('RecapFormatter — laycan partial rendering', () => {
  it('renders only laycanFrom when laycanTo is null', () => {
    const terms: RecapMainTerms = { ...MINIMAL_TERMS, laycanFrom: '2024-08-01', laycanTo: null };
    const { markdown } = formatRecap(terms);
    expect(markdown).toContain('**Laycan:** 2024-08-01');
    expect(markdown).not.toContain('to');
  });

  it('renders only laycanTo when laycanFrom is null', () => {
    const terms: RecapMainTerms = { ...MINIMAL_TERMS, laycanFrom: null, laycanTo: '2024-08-07' };
    const { markdown } = formatRecap(terms);
    expect(markdown).toContain('**Laycan:** 2024-08-07');
  });
});

describe('RecapFormatter — determinism', () => {
  it('identical input produces byte-for-byte identical output on repeated calls', () => {
    const first = formatRecap(FULL_TERMS);
    const second = formatRecap(FULL_TERMS);
    expect(first.markdown === second.markdown).toBe(true);
    expect(first.text === second.text).toBe(true);
  });

  it('mainTerms passthrough — returned mainTerms is the same object passed in', () => {
    const result = formatRecap(FULL_TERMS);
    expect(result.mainTerms).toBe(FULL_TERMS);
  });
});
