// Deterministic SUPPLYTIME 2017 recap generator — pure function, no DB, no side effects

export interface RecapMainTerms {
  vessel: string;
  vesselType: string;
  owners: string;
  charterer: string;
  hireRate: string;          // e.g. "7,500 GBP/day"
  mobilisationFee: string | null;  // e.g. "15,000 GBP" or null
  demobilisationFee: string | null;
  deliveryPort: string | null;
  redeliveryPort: string | null;
  laycanFrom: string | null;       // ISO date string or null
  laycanTo: string | null;
  period: string;                  // e.g. "30 days"
  areaOfOperation: string;         // region name
  workscope: string;               // workscope name
  governingLaw: string;            // default "English Law"
  charterParty: string;            // e.g. "SUPPLYTIME 2017"
}

export interface RecapOutput {
  mainTerms: RecapMainTerms;
  markdown: string;
  text: string;
}

/**
 * Renders the laycan field value from optional from/to strings.
 * Returns null if neither is set; partial if only one is set.
 */
function renderLaycan(from: string | null, to: string | null): string | null {
  if (from !== null && to !== null) return `${from} to ${to}`;
  if (from !== null) return from;
  if (to !== null) return to;
  return null;
}

/**
 * Generates a deterministic SUPPLYTIME 2017 recap from fixture main terms.
 * Pure function — no DB access, no side effects, no timestamps.
 * Identical input -> identical output, byte-for-byte.
 */
export function formatRecap(terms: RecapMainTerms): RecapOutput {
  const laycan = renderLaycan(terms.laycanFrom, terms.laycanTo);

  // Fixed-order field list — this order is a contract (SPEC-001 §4.7)
  const fields: Array<{ mdLabel: string; txtLabel: string; value: string | null }> = [
    { mdLabel: '**Vessel:**', txtLabel: 'Vessel:', value: `${terms.vessel} (${terms.vesselType})` },
    { mdLabel: '**Owners:**', txtLabel: 'Owners:', value: terms.owners },
    { mdLabel: '**Charterer:**', txtLabel: 'Charterer:', value: terms.charterer },
    { mdLabel: '**Hire Rate:**', txtLabel: 'Hire Rate:', value: terms.hireRate },
    { mdLabel: '**Mobilisation Fee:**', txtLabel: 'Mobilisation Fee:', value: terms.mobilisationFee },
    { mdLabel: '**Demobilisation Fee:**', txtLabel: 'Demobilisation Fee:', value: terms.demobilisationFee },
    { mdLabel: '**Delivery:**', txtLabel: 'Delivery:', value: terms.deliveryPort },
    { mdLabel: '**Redelivery:**', txtLabel: 'Redelivery:', value: terms.redeliveryPort },
    { mdLabel: '**Laycan:**', txtLabel: 'Laycan:', value: laycan },
    { mdLabel: '**Period:**', txtLabel: 'Period:', value: terms.period },
    { mdLabel: '**Area:**', txtLabel: 'Area:', value: terms.areaOfOperation },
    { mdLabel: '**Workscope:**', txtLabel: 'Workscope:', value: terms.workscope },
    { mdLabel: '**Charter Party:**', txtLabel: 'Charter Party:', value: terms.charterParty },
    { mdLabel: '**Governing Law:**', txtLabel: 'Governing Law:', value: terms.governingLaw },
  ];

  // Build Markdown — optional fields (null value) are omitted entirely
  const mdLines = fields
    .filter((f) => f.value !== null)
    .map((f) => `${f.mdLabel} ${f.value}`);

  const markdown = [
    '# Fixture Recap',
    '',
    ...mdLines,
    '',
    '---',
    '*Generated by FixtureLog*',
  ].join('\n');

  // Build plain text — same filter, same order
  const txtLines = fields
    .filter((f) => f.value !== null)
    .map((f) => `${f.txtLabel} ${f.value}`);

  const text = [
    'FIXTURE RECAP',
    '',
    ...txtLines,
    '',
    'Generated by FixtureLog',
  ].join('\n');

  return {
    mainTerms: terms,
    markdown,
    text,
  };
}
